### ISSUE TITLE
Need example using the API to find traffic stop data files for a specific agency

### ISSUE THREAD

**Issue by potto216** [MuckRock/API-examples#13]
Is there an example using the API to find traffic stop data files for a specific agency? For example, the [Pittsburgh Bureau of Police files](https://www.muckrock.com/agency/pittsburgh-130/pittsburgh-bureau-police-357/#files) 

I can use the API and specify the agency and tags with "traffic enforcement"  
```
https://www.muckrock.com/api_v1/foia/?format=json&jurisdiction=&agency=357&projects=&tags=traffic+enforcement&has_datetime_submitted=true&has_datetime_done=true&ordering=datetime_done
```
and return a collection of communications to look through for a "ffile" that may be data. However, there doesn't seem to be metadata associated with the "ffile" to define it as traffic stop data. Also it is not clear if the "traffic enforcement" tags are standardized.

If the example does not exist, I would be happy to write one and submit a PR, but it doesn't appear the metadata is available that defines the information in the "ffile". Is that correct?  Thanks!

**Comment by mitchelljkotler** [comment]
You are correct that the metadata does not exist.  The tag is not standardized and depends on users tagging their requests.

**Comment by potto216** [comment]
@mitchelljkotler thanks for the quick response and confirmation. I believe this closes the issue.
